apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Marketplace Terraform Module
    version: '20250217'
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: Gaia
            version: "latest"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/checkpoint-public/global/images/check-point-r8120-gw-byol-mig-631-991001732-v20250108
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        defaultValue: us-central1-a
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-ssd
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: integer
        defaultValue: 100
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: n1-standard-4
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue:
          - default
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: []
      - name: external_ips
        description: The external IPs assigned to the VM for public access.
        varType: list(string)
        defaultValue:
          - EPHEMERAL
      - name: ip_forward
        description: Whether to allow sending and receiving of packets with non-matching source or destination IPs.
        varType: bool
        defaultValue: false
      - name: os_version
        description: Gaia OS version
        varType: string
        defaultValue: R8120
      - name: management_interface
        description: Autoscaling Security Gateways in GCP can be managed by an ephemeral public IP or using the private IP of the internal interface (eth1).
        varType: string
        defaultValue: Ephemeral Public IP (eth0)
      - name: security_management_server_name
        description: The name of the Security Management Server as appears in autoprovisioning configuration
        varType: string
        defaultValue: checkpoint-management
      - name: configuration_template_name
        description: Specify the provisioning configuration template name (for autoprovisioning)
        varType: string
        defaultValue: gcp-asg-autoprov-tmplt
      - name: public_ssh_key
        description: This key will be used to connect to every gateway instance created by the managed instance group. This key will replace all project-wide SSH keys
        varType: string
        required: false
      - name: network_defined_by_routes
        description: Set eth1 topology to define the networks behind this interface by the routes configured on the gateway
        varType: bool
        defaultValue: true
      - name: admin_shell
        description: Change the admin shell to enable advanced command line configuration.
        varType: string
        defaultValue: /etc/cli.sh
      - name: allow_download_upload
        description: Approve to automatically download product updates and to share statistical data with Check Point for product improvement purpose. For more information see sk111080
        varType: bool
        defaultValue: true
      - name: generate_password
        description: To manage the environment's security, administrators can connect to the Management Server with SmartConsole clients and via the Gaia WebUI using this password
        varType: bool
        defaultValue: false
      - name: maintenance_mode_password
        description: Check Point recommends setting serial console password and maintenance-mode password for recovery purposes
        varType: string
        required: false
      - name: enable_stackdriver_monitoring
        varType: bool
        defaultValue: false
      - name: min_instance
        varType: integer
        defaultValue: 2
      - name: max_instance
        varType: integer
        defaultValue: 10
      - name: enable_cloud_logging
        description: Enables Cloud Logging.
        varType: bool
        defaultValue: true
      - name: enable_cloud_monitoring
        description: Enables Cloud Monitoring.
        varType: bool
        defaultValue: true
    outputs:
      - name: instance_machine_type
        description: Machine type for the compute instance.
      - name: instance_nat_ip
        description: External IP of the compute instance.
      - name: instance_network
        description: Self-link for the network of the compute instance.
      - name: instance_self_link
        description: Self-link for the compute instance.
      - name: instance_zone
        description: Zone for the compute instance.
